apiVersion: apps/v1
kind: Deployment
metadata:
  name: sdx-cleanup
  labels:
    app: sdx-cleanup
  annotations:
    replicas: {{ quote .Values.replicaCount }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: sdx-cleanup
  template:
    metadata:
      labels:
        app: sdx-cleanup
    spec:
      containers:
      - image: eu.gcr.io/{{ .Values.registry_location }}/sdx-cleanup:{{ .Chart.AppVersion }}
        imagePullPolicy: Always
        name: sdx-cleanup
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        env:
          - name: PROJECT_ID
            valueFrom:
              configMapKeyRef:
                name: sdx-config
                key: project_id
          - name: LOGGING_LEVEL
            valueFrom:
              configMapKeyRef:
                name: sdx-config
                key: logging_level
      serviceAccountName: sdx-workload-identity
